# Generated by Django 2.2 on 2020-10-10 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('document_type', models.CharField(choices=[('TI', 'tarjeta de identidad'), ('CC', 'cedula de ciudadania'), ('CE', 'cedula extranjera')], max_length=2)),
                ('document_id', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Events')),
            ],
        ),
    ]
