# Generated by Django 2.2 on 2020-10-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
